= Aaron M. Fuller
aaronfllr@gmail.com, 919.630.0768  
Raleigh, NC

== CURRENT PROJECTS

*  GO MTB Open
**  This is a project founded by me and two developer friends to fill a need in the local mountain bike community. The tech stack currently being used is Next.js and Spring Boot. We are utilizing an Adaptive Design system, and I have built a prototype for the CI/CD pipeline between the UI and the Figma designs utilizing Next.js, Figma, Storybook, and Chromatic where our eventual component tests will live.

*  The Artisan Pantry
**  This is a paid project where I am working with another developer to create a web presence for an up-and-coming bakery before they launch. The tech stack is Next.js, Supabase (Open Source Firebase alternative), Postgres, and MUI’s UI Library.

== PERSONAL PROJECTS

*  Fitness Tracker
**  This is a passion project stemming from the lack of open APIs in the trackers that I have come across. The architecture is React Native and Postgres developed in a NixOS environment. The end goal is to share workouts with friends and trainers—a much-needed feature in the Group Fitness Instructor environment.

== RELEVANT WORK EXPERIENCE

*Eliassen Group*  
Technical Recruiter (April 2021 - March 2024)
**  Created bash scripts and assigned hotkeys to automate routine tasks
**  Created an automation script to track H1B candidates for immigration advisor
**  Automated weekly tasks utilizing web scraping (Python & Selenium)
**  Built dashboards with PowerBI for metric tracking and prospecting corporations
**  Maintained GM expectations exceeding all quotas

*DSIStaff Inc*  
Technical Recruiter (promoted) (August 2019 - April 2021)
**  Built a prototype for a mobile GM calculator using Kivy framework and Python
**  Developed an understanding of older Java-based technologies and which companies are likely to utilize them

Jr. Inside Sales Representative (May 2019 - August 2019)
**  Learned about open source utilization in our product and actively worked with the Lead Database Developer
**  Utilized my healthcare background to assist with UX design and demonstrations 

*Appalachian Regional Healthcare System, Boone, NC*  
Employee Wellness Specialist (promoted) (May 2017 - October 2018)
**  Automated common day-to-day Excel tasks and created dashboards and graphs that were presented to the C-Suite
**  Conducted physiological assessments: percent body fat, flexibility, muscular strength, muscular endurance, and cardiorespiratory endurance 
**  Gave group presentations promoting our program to employees going through orientation
**  Maintained and organized health-related data for over 1000 employees 

Certified Nursing Assistant (January 2017 - May 2017)
**  Acted as patient advocate and implemented all phases of the nursing process while caring for patients efficiently
**  Accurately and efficiently input data into computer systems 

== INTERNSHIP EXPERIENCE

*Cardiopulmonary Rehabilitation Intern*  
Fall 2015
**  Read and attached varying lead configurations of ECGs daily
**  Recognized and enforced all American College of Sports Medicine guidelines for exercise testing and prescription
**  Responsible for taking multiple vitals for each patient 

== PROFICIENCIES

*  Skilled in Microsoft Office Software including PowerQuery and PowerBI
*  Learning new skills 
*  Data reporting using Excel, Tableau, and Plotly 
*  Strong personal communication skills 
*  TypeScript, Kotlin, Java, Python, JavaScript, SQL, React.js, NextJS, Selenium, Django, matplotlib
*  Breaking down complex processes into easily understood concepts 

== EXTERNAL PROJECTS

*  Starting a non-profit geared towards easing accessibility in mountain biking with a few fellow developers
*  Building an eCommerce-like site for a local bakery

== EDUCATION

*Appalachian State University*  
Bachelor of Science, Exercise Science concentration in Clinical Physiology; Minor, Psychology (August 2016)

== PROFILES

*LinkedIn:* https://www.linkedin.com/in/aaron-fuller-32776910b/  
*GitHub:* https://github.com/aaronfllr
